### PR TITLE
First version of loadseries

### PR DESCRIPTION
**Pull request by RussellMcOrmond**
Main issue https://github.com/crkn-rcdr/CIHM-Meta/issues/7

Created PR as place to discuss features as I make change commits.

### CODE REVIEW

**Comment by RussellMcOrmond** [comment]
I'm hoping the two of you can look at the Couch https://upholstery.canadiana.ca/couch/_utils/database.html?collection database and Swift https://swift-tor.canadiana.ca/v1/AUTH_crkn/access_metadata/ container to see if this matches what we are expecting, or if I have missed anything for this tool.

**Comment by RussellMcOrmond** [comment]
This is related to the documentation update in https://github.com/crkn-rcdr/Access-Platform/pull/19

Remember that there is a "dkrishnan" and "sascha" Swift accounts created, both of which have access to the access_* containers.  I can reset passwords if you need.

**Comment by RussellMcOrmond** [comment]
I'm working on doing a validation of 'collection' and 'slug' documents within the loadseries tool.

I noticed https://github.com/crkn-rcdr/Access-Platform/issues/23 from validation errors.

**Comment by SaschaAdler** [comment]
I found a what appears to be a series (NOID: 69429/s00c4sj1bk8b) that appears to have collections as items. I'm not sure how this happened.

**Comment by RussellMcOrmond** [comment]
I should have squashed before merge, so there would have been a simpler commit.

I agree about Dumper() for scripts being kept longer term, and may clean them up later if we end up running this more often.

**Pull request merged**
